services:
  web:
    build: .
    container_name: php_web
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html/pusat-kebugaran-new
    working_dir: /var/www/html/pusat-kebugaran-new
    command: php -S 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aditferrysani1+
      MYSQL_DATABASE: db_pusatkebugaran
      MYSQL_USER: psbugar
      MYSQL_PASSWORD: Adiferrysani1+
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: